screen.blit(o_image,o_rect)
        # x_rect = x_image.get_rect(center =(300,100))
        # screen.blit(x_image,x_rect)
        # x_rect = x_image.get_rect(center =(500,100))
        # screen.blit(x_image,x_rect)
        # o_rect = o_image.get_rect(center = (100,300))
        # screen.blit(o_image,o_rect)
        # x_rect = x_image.get_rect(center =(300,300))
        # screen.blit(x_image,x_rect)
        # o_rect = o_image.get_rect(center = (500,300))
        # screen.blit(o_image,o_rect)
        # x_rect = x_image.get_rect(center =(100,500))
        # screen.blit(x_image,x_rect)
        # o_rect = o_image.get_rect(center = (300,500))
        # screen.blit(o_image,o_rect)
        # x_rect = x_image.get_rect(center =(500,500))
        # screen.blit(x_image,x_rect)
